# All done by: Sepehr
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidentity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aidentity
      service: server
  template:
    metadata:
      labels:
        app: aidentity
        service: server
    spec:
      containers:
        - name: aidentity-server
          image: europe-west4-docker.pkg.dev/aidentity-1/monorepo/backend:v1
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 40
            periodSeconds: 6
            timeoutSeconds: 2
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 5
