# All done by: Sepehr
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidentity-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aidentity
      service: app
  template:
    metadata:
      labels:
        app: aidentity
        service: app
    spec:
      containers:
        - name: aidentity-app
          image: europe-west4-docker.pkg.dev/aidentity-1/monorepo/aidentity:v1
          ports:
            - containerPort: 8080
