# All done by: Sepehr
apiVersion: v1
kind: Service
metadata:
  name: aidentity-app
spec:
  selector:
    app: aidentity
    service: app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
